version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx-backend
    ports:
      - 81:80
    volumes:
      - ./docker-local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
    depends_on:
      - backend
    links:
      - backend
    restart: 'unless-stopped'

  backend:
    build: ./
    container_name: pm-backend
    volumes:
      - ./:/srv/parking-management
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_PORT=5432
      - XDEBUG_HOST=docker.for.mac.host.internal
      - DEBUG=${DEBUG}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    command: 'web'
    depends_on:
      - postgres
    links:
      - postgres
    restart: 'unless-stopped'

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    ports:
      - 6432:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    restart: 'unless-stopped'
